new post:
- _posts/*
# * is a wildcard
# lines below will apply "test" label to all repo files
# can add a certain directory to a .gitignore to ignore

#test:
#- /*

#front-end:
#- frontend/*

#back-end:
#- backend/*
